services:
  - type: web
    name: sales-king-academy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        value: LCX039E7QRA5G
