services:
  - type: web
    name: saleskingacademy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ska_autonomous_complete:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
